### PR TITLE
fix: Add AnyCPU publish file for winui

### PR DESCRIPTION
**Pull request by jeromelaban**
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno/issues/18212

## PR Type

What kind of change does this PR introduce?
- Bugfix

## What is the new behavior?

Add an AnyCPU pub file, which does not contain a runtime identifier.

### CODE REVIEW

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.4

**Comment by ArchieCoder** [comment]
@jeromelaban FYI, I have this warning in 5.4.5. Is it merged yet? I see above backport 3 days ago but I'm not sure about the Uno pipeline.

**Comment by jeromelaban** [comment]
@ArchieCoder this is only a template change. For your own project, you'll need to add the missing file manually. We'll update the uno upgrade docs.

**Comment by ArchieCoder** [comment]
@jeromelaban ⚠️ Raising the issue here for visibility. This new change causes two issues for Fluent apps:

https://github.com/unoplatform/uno/issues/18367

(Sorry, I filled one bug for two issues)

**Pull request merged**
