### PR TITLE
fix .net8 build on windows

### PR DESCRIPTION
**Pull request by limeniye**
This is just a proposition PR to fix an error with the latest .net 8

GitHub Issue (If applicable): closes https://github.com/unoplatform/uno.templates/issues/301

## PR Type

What kind of change does this PR introduce?

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current [supported SDKs](../README.md#supported)
- [ ] Docs have been added/updated which fit [documentation template](https://github.com/nventive/Uno/blob/master/doc/.feature-template.md). (for bug fixes / features)
- [ ] [Unit Tests and/or UI Tests](doc/articles/working-with-the-samples-apps.md) for the changes have been added (for bug fixes / features) (if applicable)
- [ ] [Wasm UI Tests](doc/articles/working-with-the-samples-apps.md#running-the-webassembly-ui-tests-snapshots) are not showing unexpected any differences. Validate PR `Screenshots Compare Test Run` results.
- [ ] Contains **NO** breaking changes
- [ ] Updated the [Release Notes](https://github.com/nventive/Uno/tree/master/doc/ReleaseNotes)
- [ ] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by dansiegel** [comment]
After discussing this with @nickrandolph we don't feel this is the appropriate change to be making as this is instead a hack to revert to the previous behavior instead of fixing the actual issue and bringing this into alignment with .NET 8

**Comment by limeniye** [comment]
Good!
Thank you for viewing my issue!

**Comment by nickrandolph** [comment]
You might be interested in this commit which does adjust the RIDs from win10 to just win: https://github.com/unoplatform/uno.templates/pull/291/commits/8676ee9bb6ec62896edc8561dff772d5ac5f074d

**Comment by limeniye** [comment]
@nickrandolph, Indeed, it helps with this problem.
Thank you for the answer!

**Pull request closed without merging**
