### PR TITLE
fix: change comment to be JSON valid

### LINKED ISSUE #767: [Bug] Invalid JSON (comment) in global.json shows up as error
### Current behavior

The `global.json` file used for templates is **NOT** valid JSON - since comments are not allowed in the format.

While this works in practice it's not 

This makes VSCode always shows an error inside the file (filename is in red in the file explorer).

You can also see this inside the github editor itself

```json
{
  // To update the version of Uno please update the version of the Uno.Sdk here. See https://aka.platform.uno/upgrade-uno-packages for more information.
  "msbuild-sdks": {
    "Uno.Sdk": "$UnoSdkVersion$"
  }
}
```

[link](https://github.com/unoplatform/uno.templates/blob/main/src/Uno.Templates/content/unoapp/global.json#L2)

### Expected behavior

To avoid tooling errors we need to use JSON-valid _pseudo comments_ like

```json
{
  "msbuild-sdks": {
    "//": "To update the version of Uno please update the version of the Uno.Sdk here. See https://aka.platform.uno/upgrade-uno-packages for more information.",
    "Uno.Sdk": "5.2.0-dev.2103"
  }
}
```

That makes both Github and VS Code happier.

### Affected platforms

_No response_

### Template Host

dotnet new

### Host OS

macOS

### Template Options

Anything that produce a Uno app project with the `global.json` file.

### Template Version

```shell
This is still the case with the git version.
```

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by spouliot**
GitHub Issue (If applicable): closes #767 

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

The global.json file used for templates is NOT valid JSON - since comments are not allowed in the format.

## What is the new behavior?

Comment was changed to fit the JSON format.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Associated with an issue (GitHub or internal)

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by jojorne** [comment]
Comments in global.json files are supported using JavaScript or C# style comments. - [Comments in global.json](https://learn.microsoft.com/en-us/dotnet/core/tools/global-json#comments-in-globaljson)

**Review by Xiaoy312 — APPROVED** [review]

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.2

**Comment by jeromelaban** [comment]
@mergifyio backport release/stable/5.3

**Comment by jeromelaban** [comment]
Let's not merge this one, we'll use the jsonc config.

**Pull request closed without merging**
